// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwzeX9lyRQts0UqeUGsaBPOwnpEMdVGxY',
    appId: '1:651038666741:web:258bb1be3341819709babc',
    messagingSenderId: '651038666741',
    projectId: 'speedmatharena',
    authDomain: 'speedmatharena.firebaseapp.com',
    storageBucket: 'speedmatharena.firebasestorage.app',
    measurementId: 'G-JQ6CF2TDVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk365oKCONsJbz0QOj1rdHF2Swv4rrDcM',
    appId: '1:651038666741:android:dc96ae96442ca18909babc',
    messagingSenderId: '651038666741',
    projectId: 'speedmatharena',
    storageBucket: 'speedmatharena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDpCY1McuWL1Saba6qtAti9FQM8j-W2I',
    appId: '1:651038666741:ios:ad7b949d1692914409babc',
    messagingSenderId: '651038666741',
    projectId: 'speedmatharena',
    storageBucket: 'speedmatharena.firebasestorage.app',
    iosBundleId: 'com.example.speedmathArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDpCY1McuWL1Saba6qtAti9FQM8j-W2I',
    appId: '1:651038666741:ios:ad7b949d1692914409babc',
    messagingSenderId: '651038666741',
    projectId: 'speedmatharena',
    storageBucket: 'speedmatharena.firebasestorage.app',
    iosBundleId: 'com.example.speedmathArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwzeX9lyRQts0UqeUGsaBPOwnpEMdVGxY',
    appId: '1:651038666741:web:198963b1a709969b09babc',
    messagingSenderId: '651038666741',
    projectId: 'speedmatharena',
    authDomain: 'speedmatharena.firebaseapp.com',
    storageBucket: 'speedmatharena.firebasestorage.app',
    measurementId: 'G-WGW22BX8VR',
  );
}
